[build-system]
requires = ["hatchling", "jupyterlab>=4"]
build-backend = "hatchling.build"

[project]
name = "jlab-ws-chat-extension"
version = "0.1.0"
description = "WebSocket chat panel for JupyterLab"
authors = [{ name = "Chas Murray", email = "rcmurray@andrew.cmu.edu" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["jupyterlab>=4.0.0"]

[project.entry-points."jupyterlab.extension"]
jlab-ws-chat-extension = "jlab_ws_chat_extension"

[tool.hatch.build]
include = ["jlab_ws_chat_extension/**"]

[tool.hatch.build.targets.wheel]
include = [
  "jlab_ws_chat_extension/**",
  "jlab_ws_chat_extension/labextension/**",
  "jlab-ws-chat-extension.json",
  "frontend/package.json",
  "frontend/lib/**"
]

[tool.hatch.build.targets.wheel.shared-data]
"jlab_ws_chat_extension/labextension" = "share/jupyter/labextensions/jlab-ws-chat-extension"
