apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: k8s-jhub-secret
    shareName: k8s-jhub-share-2
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=10000
    - gid=10000
    - mfsymlinks
    - nobrl
  storageClassName: default