[build-system]
requires = ["setuptools>=61", "jupyter_packaging>=0.10"]
build-backend = "setuptools.build_meta"

[project]
name = "jlab-chat-ext"
version = "0.1.0"
description = "A JupyterLab extension for chat."
readme = "README.md"
# Use license-files to resolve the deprecation warning
license-files = ["LICENSE"]
requires-python = ">=3.8"
authors = [
    { name = "Chas Murray", email = "rcmurray@andrew.cmu.edu" },
]
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    # The "License" classifier is deprecated, so we remove it.
    "Programming Language :: Python :: 3",
]
dependencies = [
    "jupyter_server",
]

[project.urls]
Homepage = "https://github.com/DANCEcollaborative/jlab-chat-ext"
Repository = "https://github.com/DANCEcollaborative/jlab-chat-ext"

[tool.jupyter-packaging]
options = { "managed-dependencies" = true }
source-dir = "frontend"
dest-dir = "jlab_chat_ext/labextension"

# NEW section to solve the main error
[tool.setuptools.packages.find]
# We only want to find packages in the current directory
where = ["."]
# And we only want to include "jlab_chat_ext"
include = ["jlab_chat_ext"]