apiVersion: v1
kind: Pod
metadata:
  name: k8s-jhub-workload-identity
  namespace: jhub
  labels:
    azure.workload.identity/use: "true"  # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: workload-identity-service-acct
  containers:
    - image: k8sjhubacr
      name: k8s-jhub-workload-id-container
