hub:
  config:
    JupyterHub:
      authenticator_class: dummy
  extraConfig:
    rtc-config: |
      c.LabApp.collaborative = True
singleuser:
  image:
    name: k8shubacr.azurecr.io/jupyterhub-rtc
    tag: latest
  cmd: ["start-notebook.sh",]
  memory:
    limit: 2G
    guarantee: 1G
  cpu:
    limit: 2
    guarantee: 0.5
  storage:
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: jupyterhub-shared-pvc
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared
  extraEnv:
    JUPYTER_ENABLE_LAB_RTC: "1"
    NO_PROXY: "collab.lti.cs.cmu.edu,52.255.216.201,localhost,127.0.0.1"
    no_proxy: "collab.lti.cs.cmu.edu,52.255.216.201,localhost,127.0.0.1"
