FROM node:20

# Create app directory
WORKDIR /home/node/app

# Install dependencies
COPY backend/package*.json ./
RUN yarn install

# Copy source code
COPY backend/ .

# Expose port used by chat server
EXPOSE 3001

CMD ["node", "server.js"]
