[build-system]
requires = ["hatchling", "jupyterlab>=4"]
build-backend = "hatchling.build"

[project]
name = "jlab-ws-chat-extension"
version = "0.1.0"
description = "WebSocket chat panel for JupyterLab"
authors = [{ name = "Chas Murray", email = "rcmurray@andrew.cmu.edu" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["jupyterlab>=4.0.0"]

[project.entry-points."jupyterlab.extension"]
jlab-ws-chat-extension = "jlab-ws-chat-extension"

[tool.hatch.build]
include = [
    "jlab-ws-chat-extension/**",
]

[tool.hatch.build.targets.wheel]
include = [
  "jlab-ws-chat-extension/**",
  "jlab-ws-chat-extension/labextension/**",
  "jlab-ws-chat-extension.json",
  "frontend/package.json",
  "frontend/lib/**"
]

[tool.hatch.build.targets.wheel.shared-data]
"jlab-ws-chat-extension/labextension" = "share/jupyter/labextensions/jlab-ws-chat-extension"

[tool.jupyter-packaging]
prebuilt = true

[tool.jupyter-packaging.metadata]
name = "jlab-ws-chat-extension"
prebuilt = true

[tool.jupyter-packaging.options]
ensured-targets = ["jlab-ws-chat-extension/labextension/lib/index.js"]
data_files = [
  [
    "share/jupyter/labextensions/jlab-ws-chat-extension",
    "jlab-ws-chat-extension/labextension",
    "**"
  ],
  [
    "etc/jupyter/jupyter_server_config.d",
    ".",
    "jlab-ws-chat-extension.json"
  ]
]

[tool.jupyter-packaging.build-frontend]
name = "jlab-ws-chat-extension"
path = "frontend"
install = true
build_cmd = "jlpm build"
source_dir = "frontend"
output_dir = "jlab-ws-chat-extension/labextension"
