[build-system]
requires = ["hatchling", "jupyterlab>=4"]
build-backend = "hatchling.build"

[project]
name = "jlab_ws_chat_extension"
version = "0.1.0"
description = "WebSocket chat panel for JupyterLab"
authors = [{ name = "Chas Murray", email = "rcmurray@andrew.cmu.edu" }]
license = "MIT"
readme = "README.md"
dependencies = []

[project.entry-points."jupyterlab.extension"]
jlab-ws-chat-extension = "jlab_ws_chat_extension"

[tool.hatch.build.targets.wheel]
include = [
  "jlab_ws_chat_extension/**",
  "jlab_ws_chat_extension/labextension/**",
  "jlab_ws_chat_extension.json"
]

[tool.jupyter-packaging.metadata]
name = "jlab-ws-chat-extension"
prebuilt = true
# extension = true

[tool.jupyter-packaging.options]
ensured-targets = ["jlab_ws_chat_extension/labextension/lib/index.js"]
data_files = [
  [
    "share/jupyter/labextensions/jlab-ws-chat-extension",
    "jlab_ws_chat_extension/labextension",
    "**"
  ],
  [
    "etc/jupyter/jupyter_server_config.d",
    ".",
    "jlab_ws_chat_extension.json"
  ]
]

[tool.jupyter-packaging.build-frontend]
name = "jlab_ws_chat_extension"
path = "frontend"
