singleuser:
  image:
    name: k8sjacr.azurecr.io/jupyter-chat
    tag: latest
    pullPolicy: Always
  storage:
    type: dynamic
    extraVolumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
    extraVolumeMounts:
      - name: shared-data
        mountPath: /home/jovyan/shared
  lifecycleHooks:
    postStart:
      exec:
        command:
          - bash
          - -c
          - |
            source /etc/profile.d/start-chat.sh

hub:
  config:
    JupyterHub:
      admin_users:
        - admin

---
# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

#   extraEnv:
#     JUPYTER_ENABLE_LAB_RTC: "1"
#     NO_PROXY: "collab.lti.cs.cmu.edu,52.149.131.64,135.234.248.176,localhost,127.0.0.1"
#     no_proxy: "collab.lti.cs.cmu.edu,52.149.131.64,135.234.248.176,localhost,127.0.0.1"
